apiVersion: v1
kind: Service
metadata:
  name: resumes-joseaeltala
  labels:
    app: resumes
    who: joseaeltala
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
      name: http
  selector:
    app: resumes
    who: joseaeltala
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: resumes-joseaeltala
  labels:
    app: resumes
    who: joseaeltala
spec:
  selector:
    matchLabels:
      app: resumes
      who: joseaeltala
  template:
    metadata:
      namespace: resumes
      labels:
        app: resumes
        who: joseaeltala
    spec:
      containers:
      - image: "${IMAGE}"
        imagePullPolicy: Always
        name: resumes-joseaeltala
        env:
        - name: CV_TITLE
          value: "Jose Ángel Ael Talavera"
        resources:
          requests:
            cpu: "100m"
            memory: "128M"
          limits:
            cpu: "1000m"
            memory: "512M"
        ports:
        - containerPort: 80
          protocol: TCP
          name: http
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: resumes-joseaeltala-ingress
  labels:
    name: resumes-joseaeltala-ingress
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
  - hosts:
    - blueclouds.es
    secretName: gitlab-tls
  rules:         
  - host: blueclouds.es
    http:
      paths:
      - path: /resumes/joseaeltala
        pathType: Prefix
        backend:
          service:
            name: resumes-joseaeltala
            port:
              number: 80